### ISSUE TITLE
"appinst: command not found" despite installing

### ISSUE THREAD

**Issue by zillionbear** [akemin-dayo/AppSync#104]
Tring to run `appinst` tells me the command was not found. Tested as root in both MobileTerminal and over SSH, rebooted per instructions as well.

**Comment by akemin-dayo** [comment]
Can you run this in a Terminal session as `root` and paste the output here?

```shell
find / | grep appinst
```

**Comment by zillionbear** [comment]
I ran it as `root` and it returned nothing.. maybe I did something wrong?

**Comment by akemin-dayo** [comment]
That seems to indicate that appinst isn't actually installed on your system. At the very least, you should be able to see `dpkg` files pertaining to appinst.

If `dpkg -l | grep appinst` turns up nothing as well, then just make sure you've actually installed it.

**Comment by zillionbear** [comment]
I managed to miss appinst multiple times while installing AppSync Unified, haha

**Comment by akemin-dayo** [comment]
Ah… it's okay, mistakes happen. ;P

I'll close this issue then〜
