### ISSUE TITLE
Without substrate?

### ISSUE THREAD

**Issue by SmartBoy84** [akemin-dayo/AppSync#125]
Theoretically, your code is sufficient for an AMFI bypass, right? Is it possible to inject without substrate loaded?

**Comment by akemin-dayo** [comment]
> Theoretically, your code is sufficient for an AMFI bypass, right?
AppSync Unified has _nothing_ to do with an AMFI bypass.

> Is it possible to inject without substrate loaded?
ASU requires the Substrate libraries/frameworks to be present, but does not depend on the Substrate code injector itself.
