### ISSUE TITLE
could you support the Xina A15 iOS 15 jailbreak?

### ISSUE THREAD

**Issue by wwpp3399** [akemin-dayo/AppSync#131]
thx!!!!!

**Comment by akemin-dayo** [comment]
Are you willing to test a beta build of AppSync Unified to see if it works on your device? If so, what iOS version do you have?

**Comment by wwpp3399** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
    
    

    

    I have a 13pro run at iOS 15.0, I can test for you.
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/14/2022 21:52
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [akemin-dayo/AppSync] could you support the Xina A15 iOS 15 jailbreak? (Issue #131)
        
      
    
  
  
Are you willing to test a beta build of AppSync Unified to see if it works on your device? If so, what iOS version do you have?

**Comment by shatyuka** [comment]
seems works fine for iOS 15.6.1, palera1n jailbreak.

**Comment by wwpp3399** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    So I hope you to update it for xina
    
        
            
        
    
    
    
    

    

    

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        12/15/2022 10:53
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [akemin-dayo/AppSync] could you support the Xina A15 iOS 15 jailbreak? (Issue #131)
        
      
    
  
  
seems works fine for iOS 15.6.1, palera1n jailbreak.

**Comment by shatyuka** [comment]
Just modify the maximum firmware version. https://github.com/akemin-dayo/AppSync/blob/12314a68c79b752ffd463f3cf5c01caef802d82f/control#L2

**Comment by wwpp3399** [comment]
I modified the maxiimum firmware version and build with make packge command line , I install net.angelxwind.appsyncunified_104.0_iphoneos-arm.deb, then I reboot my device and use xina to jailbreak agin, it does not work for install no signature ipa.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/4317010/207770824-255f4e17-a7ed-48e6-a48a-8e7cbbfaa161.png">

**Comment by shatyuka** [comment]
Damn maybe it works on my machine because of `ldid`. I'll look into it later.

**Comment by wwpp3399** [comment]
thanks

**Comment by shatyuka** [comment]
iOS15 has a new property `SignerType`. PR soon.

**Comment by wwpp3399** [comment]
thank you so much

**Comment by wwpp3399** [comment]
I tried this pr, but it not work 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/4317010/208008854-950cd4ce-acc6-4365-a3ff-fef1c27f84a6.png">

**Comment by wwpp3399** [comment]
not work
<img width="566" alt="image" src="https://user-images.githubusercontent.com/4317010/208013214-821b3092-0ba0-4005-8126-cf5b8659efe1.png">

I removed the embedded provisioning profile in the ipa.

**Comment by wwpp3399** [comment]
not work
<img width="571" alt="image" src="https://user-images.githubusercontent.com/4317010/208013822-b832d9fc-49b9-4aed-b54d-82e3fb59b97d.png">
I removed the embedded provisioning profile in the ipa.
I found some error when install it;

![IMG_0004](https://user-images.githubusercontent.com/4317010/208014082-b66d00a9-3e71-47b1-b507-66be80d3637b.PNG)

**Comment by shatyuka** [comment]
> Is ASU working only with palera1n but not XinaA15 at this time…? (I'll be able to test soon)

IDK, I don't have an embedded-provisioning ipa, neither an iOS 14 device to determine whether it works before XD.
