### ISSUE TITLE
appsync not working

### ISSUE THREAD

**Issue by SiCole180421** [akemin-dayo/AppSync#136]
hi.

my ipad is running iPadOS 16.2, jailbroken with palera1n and have appsync installed. i have done what is neeeded to activate appsync and that is rebooting and rejailbreaking but when im installing an ipa unsigned, ad-hoc signed etc, those apps immediately crash on launch. ive also downgraded to iPadOS 15.6RC1 just incase it was an iPadOS16 issue but the same thing happens

**Comment by jacklee-code** [comment]
same problem here. running  iOS 15.1.1 and jailbroken with Xinaa15 latest version. Successfully install the ipa but crash when the installed ipa crashed after launch

**Comment by akemin-dayo** [comment]
If the app has successfully been installed, then AppSync Unified and appinst have done their job correctly.

Most likely, the IPAs you are trying to install are incorrectly fakesigned, as seen in #169. Solutions are provided in my comment there.
