### ISSUE TITLE
iOS 16.1.3 support 

### ISSUE THREAD

**Issue by Hammu778** [akemin-dayo/AppSync#148]
Please add iOS 16.1.3 support if possible. If not I completely understand. Thanks!

**Comment by favna** [comment]
Don't you mean 16.3.1? At any rate, you should follow Karen on Twitter for updates and you would've seen https://twitter.com/akemin_dayo/status/1632599012435193856?cxt=HHwWgMDTzdyJlKgtAAAA

**Comment by Hammu778** [comment]
> Don't you mean 16.3.1? At any rate, you should follow Karen on Twitter for updates and you would've seen https://twitter.com/akemin_dayo/status/1632599012435193856?cxt=HHwWgMDTzdyJlKgtAAAA

Yea

**Comment by akemin-dayo** [comment]
AppSync Unified 110.0 now supports iOS 16.3.1.
