### ISSUE TITLE
Support for jailbreaks in "Rootless" mode

### ISSUE THREAD

**Issue by bakirfatah99** [akemin-dayo/AppSync#155]
Pls update appsync to fugu max 15

**Comment by bakirfatah99** [comment]
He need support to rootless when you update?

**Comment by bakirfatah99** [comment]
Support your Tweak settings on the jailbreak Fugu15 & Unc0ver & etc...!

**Comment by bakirfatah99** [comment]
Support your Tweak settings on the jailbreak Fugu15 & Unc0ver & etc...!



https://t.co/5NMElJBRnZ

**Comment by bakirfatah99** [comment]
Tweak for support rootless


https://t.co/cnbiWLBk8V

**Comment by bakirfatah99** [comment]
When will you update, please?

**Comment by bakirfatah99** [comment]
We waited a long time

**Comment by akemin-dayo** [comment]
Support for "rootless" mode jailbreaks is coming. I have a test device available already, I just have other commitments I must attend to first.

**Comment by bakirfatah99** [comment]
very good. Please update as soon as we need it. Good luck

**Comment by JEmlay** [comment]
Subbing for rootless update.  Thanks for working on it!

**Comment by bakirfatah99** [comment]
This 30 days he cant update appsync

**Comment by 908875137** [comment]
Subbing for rootless update. Thanks for working on it!

**Comment by akemin-dayo** [comment]
Full support for "rootless" mode jailbreaks will be coming within the next week or so. Apologies for the wait.

**Comment by JEmlay** [comment]
Awesome, thanks fort he update!

**Comment by lisiyaki** [comment]
（お楽しみに待っています！）

**Comment by bakirfatah99** [comment]
This next week when you release pls

**Comment by bakirfatah99** [comment]
Pls where this update 2 weeks ago you no update :((((

**Comment by akemin-dayo** [comment]
I've been coordinating with external testers for both ASU and other tweaks, as supporting rootless has required me to update my own internal tooling, as well.

https://twitter.com/akemin_dayo/status/1662792772099923972

**Comment by JEmlay** [comment]
Awesome, thank you for all your work!

**Comment by bakirfatah99** [comment]
Good work :)

**Comment by bakirfatah99** [comment]
This week will be release appsync new update?

**Comment by iwannet** [comment]
When will it be done ?

**Comment by bakirfatah99** [comment]
Where update alo

**Comment by Shanakthra** [comment]
Eagerly awaiting rootless support. Thanks as always

**Comment by asdfzxcvbn** [comment]
you guys need to be patient omg 😭😭

it's coming soon. just wait.

**Comment by bakirfatah99** [comment]
Where this update appsync support dopamine 😂

**Comment by iwannet** [comment]
Lol it was 2 months ago

**Comment by akemin-dayo** [comment]
There… was no release 2 months ago, not sure what you're seeing there.

I'm currently working on it and trying to figure out the cause of this strange userspace reboot issue.

**Comment by iwannet** [comment]
The time someone first asked for the update was indeed 2 months ago

**Comment by bakirfatah99** [comment]
If you have support beta pls send me

**Comment by bakirfatah99** [comment]
Today New Update ?

**Comment by akemin-dayo** [comment]
AppSync Unified 112.0 has been released, with support for all iOS versions up to iOS 16.5.1, as well as "rootless" mode jailbreaks.

(※ Users using the Dopamine jailbreak may encounter issues.)

https://reddit.com/r/jailbreak/comments/14otear

**Comment by iwannet** [comment]
Thanks love to you 😀

**Comment by JEmlay** [comment]
Awesome!  Yeah, no go on Dopamine but other rootless works so far.  Just a few apps installed.

Hopefully AFC support to follow.  Then I can finally get all my game saves transferred to my newly jailbroken iPad!  WHY WHY WHY can't apple just let us handle our save data!
