### ISSUE TITLE
Add support for ios 16.4 rootless palera1n

### ISSUE THREAD

**Issue by iwannet** [akemin-dayo/AppSync#164]
Could you please add support for ios 16.4 rootless palera1n cuz now i need to use trollstore but appsync unified is much better, Thanks.

**Comment by akemin-dayo** [comment]
Duplicate of https://github.com/akemin-dayo/AppSync/issues/155.

Full support for "rootless" mode jailbreaks will be coming within the next week or so. Apologies for the wait.

**Comment by iwannet** [comment]
Thank you very much
