### ISSUE TITLE
Install as RPM?

### ISSUE THREAD

**Issue by systemd11** [akemin-dayo/AppSync#165]
Hi, is there any way to get this as a rpm?
Kind regards.

**Comment by RothSad110** [comment]
> Hi, is there any way to get this as a rpm?
> 
> Kind regards.

**Comment by akemin-dayo** [comment]
While Theos _does_ support building RPM packages, there is no commonly-available iOS jailbreak bootstrap that uses the RPM package manager.

As this project is open-source, you are free to try building an RPM yourself, though I'm not sure what you would do with it given the complete inability to actually install or use it.
