### ISSUE TITLE
Support for ios 16.5

### ISSUE THREAD

**Issue by DanThePman** [akemin-dayo/AppSync#168]
ios 16.5 and 16.5.1 have been released recently.
Are there any plans to add support for those versions and are any problems known so far?

**Comment by DanThePman** [comment]
By installing a modified deb file of AppSync which tolerates ios 16.5.1 everything works fine.
So AppSync works for 16.5.1 as well without problems (at least for me).

**Comment by Quirkychai** [comment]
Can u do send me the file nishanth22@gmail.com. Thank you

**Comment by akemin-dayo** [comment]
I was originally intending on releasing the next update with support for the newer iOS versions as well as rootless jailbreaks, but considering that I've [ran into a wall when it comes to support for the Dopamine jailbreak](https://twitter.com/akemin_dayo/status/1672982839405723651), I think I might just release what I have as-is with the disclaimer that it may not work correctly with Dopamine.

**Comment by rebelm8877** [comment]
hello i also need help ios 16.5 appsync not working

**Comment by rebelm8877** [comment]
hello i also need help ios 16.5 appsync not working

**Comment by Quirkychai** [comment]
I'm gonna try updating to 16.5.1 and install modified appsync unified

**Comment by Quirkychai** [comment]
Is yours rootless or rootful?

**Comment by rebelm8877** [comment]
rootless

**Comment by Quirkychai** [comment]
Apparently appsync doesnt support rootless for now.... But mine on rootful also isnt working as expected!

**Comment by rebelm8877** [comment]
then there is probably no way at the moment

**Comment by Quirkychai** [comment]
But [DanThePman](https://github.com/DanThePman) got it working

**Comment by rebelm8877** [comment]
then someone should share the info with us :)
where is the modified deb file from AppSync?

**Comment by JEmlay** [comment]
She was pretty clear in her last comment.  She hasn't rolled out the updates for newer versions yet.  Until then it's not going to work.  The repo flat out states "This version is compatible with iOS 5.0 to 16.3.1.".  Whatever DanThePman was talking about with having no issues with 16.5.1 should be taken with a grain of salt.  Sounds like malarkey to me.

**Comment by DanThePman** [comment]
Its unclear to me why I would spread false information when reporting the project's functionality for newer ios versions to the developer.
Besides that Im not using dopamine but palera1n on ios 16.5.1.

AppSync's latest binary can be found at ios-repo-updates and its version requirement can be modified by extracting and repacking the deb file in Filza.
mobilesubstrate dependency is needed as well.

**Comment by JEmlay** [comment]
Because it's been verified by multiple people (including the developer) that it does not work versus your single claim of "without problems".

As for rootless it doesn't work at all yet.  That wasn't even in question.

**Comment by DanThePman** [comment]
To my knowledge the developer only claimed that AppSync doesnt work in conjunction with the dopamine jailbreak which again is not what Im using.
This issue ticket was not intended to uniformly claim AppSync is working on every single device for ios 16.5.x but as I stated "at least for me" it is indeed working using palera1n rootful jailbreak on my iphone X with ios 16.5.1 when modifying the framework version requirement which is not difficult to do.
In fact I applied the jailbreak only a few days ago after completely resetting my phone so Im fairly confident that this simple approach of using a modified binary is even reconstructable on similiar devices as Im not running any special voodoo magic.

**Comment by JEmlay** [comment]
"I was originally intending on releasing the next update **_with support for the newer iOS versions_**".

Meaning there is no support for newer iOS versions.  Telling people to just do it is very disingenuous and reckless.  No one should do that lightly and should understand the risks in doing as such.

**Comment by DanThePman** [comment]
First off I didnt tell anyone to install officially unsupported software.
I only reported to the developer that the latest version of AppSync is indeed working on my phone which in fact was the claim that you doubted while clearly being aware that Im talking about modified version that is officially not supported.
After you indicating that I would spread false information I further elaborated what I did which again is not an install instruction
but a documentation for the developer because thats what issue tickets on github are meant for.
Github issue tickets are meant for the development teams to gain information and solve software related problems.

**Comment by JEmlay** [comment]
Again, multiple people have reported it not working on higher version of iOS.  I simply pointed that out.  You can stop taking offense to my warnings.  They are unwarranted.

"without problems" = untrue for 99.9999999% of all users.  That's what I'm getting across because I found your original statement to be disingenuous for most people.  They should know FOR FACT that it's not supported, doesn't work and should probably not try it unless they understand the risks.

If you disagree with that, great I guess.  Weird hill to stand on.  However it's reality.

"Github issue tickets are meant for the development teams to gain information and solve software related problems."

Wrong again.  They are also for finding trouble shooting information , for ANYONE to discuss the project's topic at hand along with endless other uses.  YOU do not get to tell people how to use Github.

As you can see from the back and forth above you confused people.  Mainly because your information was no good.  I stepped in to clear that up.  You are welcome.

**Comment by DanThePman** [comment]
I do not intend to offend anyone nor do I try to confuse others.
In fact I commented on this ticket to bring better clarification to the developer on the state of future ios version support.
The fact that I successfully install AppSync on my genuin and freshly setup ios phone is objectively a fact that for certain ios devices the latest AppSync version is supported for ios 16.5.1 no matter if you want to believe that or not.
Its not like my iphone x device is unique in relation to the rest of the market and again Im fairly confident that when trying to reconstruct it on different gsm iphone x devices, which I let up to the development team and not to the end user, the same result could be achieved.
Besides that people using the issue ticket on github are undisputedly well aware of the fact that github is a development platform and the issue section is not the right place to provide fully stable software.
Every user on github should be aware that issues and discussions often evolve around potentially unfinished software and that is not my own opinion but a fundamental necessity to even declare github a development platform.

**Comment by DanThePman** [comment]
I documented my experience using the latest officially unsupported version of the app on ios 16.5.1 as well as I could however whats being considered useful is solely up to the development team.
