### ISSUE TITLE
Appsync dont work for dopamine jailbreak

### ISSUE THREAD

**Issue by bakirfatah99** [akemin-dayo/AppSync#175]
Pls appsync support for dopamine

**Comment by bakirfatah99** [comment]
I need it so badly appsync

**Comment by bakirfatah99** [comment]
Dopamine jailbreak isn't it good?

**Comment by bakirfatah99** [comment]
????????

**Comment by akemin-dayo** [comment]
This is now a duplicate of #174. Please track that issue and move all discussion to it.
