### ISSUE TITLE
[ElleKit checkm8 rootless jb bug report]

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [akemin-dayo/AppSync#187]
AppSync failed to work successfully. It always in the step of the installation process shows this error using Filza: Cannot communicate with helper application

The OS version I'm using is iOS 15.4.1 arm64

The jailbreak is Palera1n rootless

When I try to install jailbreak apps from the internet, it shows App not available (not installed succesfully) and also AppStore and normal sideloading is also failed as long as I keeping AppSync Unified installed on my device

Can some research be done and this bug gets fixed because without that fix, the AppSync Unified is basically useless for us 😔

**Comment by akemin-dayo** [comment]
This is the same issue as #174 and is unfortunately not something I can fix, as the problem lies within ElleKit.

Évelyne (the developer of ElleKit) will have to fix it on her end.

While I am closing this issue, please do feel free to continue discussion in #174.
