### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by pedrocasmw** [akemin-dayo/AppSync#217]
Hi,
I'm trying to compile the code but the following error is occurring:

![image](https://github.com/user-attachments/assets/11e1756b-e83a-494b-ba0e-009047f3c058)
...
![image](https://github.com/user-attachments/assets/07b76c27-413d-4430-b859-da184d69bd04)

I installed theos following the instructions on the website.

**Comment by difaagh** [comment]
> Hi, I'm trying to compile the code but the following error is occurring:
> 
> ![image](https://private-user-images.githubusercontent.com/168434267/356841022-11e1756b-e83a-494b-ba0e-009047f3c058.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzA0NDksIm5iZiI6MTcyMzk3MDE0OSwicGF0aCI6Ii8xNjg0MzQyNjcvMzU2ODQxMDIyLTExZTE3NTZiLWU4M2EtNDk0Yi1iYTBlLTAwOTA0N2YzYzA1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODM1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmQ3MzAyOWI1NjMyMzhhMTMxNDY4MjNiMTM4NGZjNDk3NTY3ODE3YjI5ODYwMTI2NTI0NTVkMmQ0NjNhMDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HjE5bKzMliHHJnu5lXZo_IEe9any7u5NUGYiFH0gffA) ... ![image](https://private-user-images.githubusercontent.com/168434267/356841040-07b76c27-413d-4430-b859-da184d69bd04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzA0NDksIm5iZiI6MTcyMzk3MDE0OSwicGF0aCI6Ii8xNjg0MzQyNjcvMzU2ODQxMDQwLTA3Yjc2YzI3LTQxM2QtNDQzMC1iODU5LWRhMTg0ZDY5YmQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwODM1NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWY2ZjNlMDc4YjAyMzg3OGQ0MWI2NTNlZjA4YTk3YjgzMWI2YjFhZjdjNzNlNmE0OTU1N2IyMGU1MTYyMzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Mme_YrZjQctm-CJyeLjtt3kon3p2aDnWXE8o0dt8Vlo)
> 
> I installed theos following the instructions on the website.

i also got the same error when using Xcode 15.4.

**Comment by alright21** [comment]
Hi! I managed to compile by substituting the macros with the hardcoded values of the strings (see my fork). Unfortunately, I am not able to create the deb package for arm64, maybe you can help me with that

**Comment by Serena1432** [comment]
Sorry for being late and I don't know if the OP has already fixed this issue, but if the OP or any people coming here having the same issue, I just found a way to fix that issue above:

https://gist.github.com/Serena1432/10763b73c8bcfa8c2d203c759a56b089

But yes I also hope Karen will come back soon and make an update to properly solve the issue cuz it has been over a year since the last update 😭 😭 😭

**Comment by pedrocasmw** [comment]
> Sorry for being late and I don't know if the OP has already fixed this issue, but if the OP or any people coming here having the same issue, I just found a way to fix that issue above:
> 
> https://gist.github.com/Serena1432/10763b73c8bcfa8c2d203c759a56b089
> 
> But yes I also hope Karen will come back soon and make an update to properly solve the issue cuz it has been over a year since the last update 😭 😭 😭

It works perfectly. Thanks.
The iOS SDK can be obtained from Theos's github:
https://github.com/theos/sdks/releases

**Comment by difaagh** [comment]
> Sorry for being late and I don't know if the OP has already fixed this issue, but if the OP or any people coming here having the same issue, I just found a way to fix that issue above:
> 
> 
> 
> https://gist.github.com/Serena1432/10763b73c8bcfa8c2d203c759a56b089
> 
> 
> 
> But yes I also hope Karen will come back soon and make an update to properly solve the issue cuz it has been over a year since the last update 😭 😭 😭 

thank you @Serena1432 🔥
i think can mark this as closed @pedrocasmw

**Comment by alright21** [comment]
> Sorry for being late and I don't know if the OP has already fixed this issue, but if the OP or any people coming here having the same issue, I just found a way to fix that issue above:
> 
> https://gist.github.com/Serena1432/10763b73c8bcfa8c2d203c759a56b089
> 
> But yes I also hope Karen will come back soon and make an update to properly solve the issue cuz it has been over a year since the last update 😭 😭 😭

Thank you very much! My solution was really unpolished, yours seem more stable and more "I know what's going on":)
