### ISSUE TITLE
Works with iOS 14.7.1

### ISSUE THREAD

**Issue by Doregon** [akemin-dayo/AppSync#80]
I'm back with another support issue, this time with good news about iOS 14.7.1 and lower.

**Comment by n0thing2speak** [comment]
how to add it ,the repo says <=14.6

**Comment by 0x3c3e** [comment]
@n0thing2speak basically follow https://unix.stackexchange.com/a/138190 and edit DEBIAN/control file
You can download the deb here https://cydia.akemi.ai/debs/

**Comment by akemin-dayo** [comment]
Thanks @Doregon! Been busy with various other things, sorry for the delay > <
