### ISSUE TITLE
Three App Limit even with AppSync

### ISSUE THREAD

**Issue by jschiefner** [akemin-dayo/AppSync#81]
Hi, i'm trying to install apps that i wrote in XCode with AppSync to avoid having to reinstall them every 7 days. I got AppSync Unified from your Repo and built the apps in xcode using the `Any iOS Device (arm64)` target. Then i wrapped the resulting .app file in a Payload Folder, zipped it and renamed it to a .ipa file. Then i tried several installation methods:
 - filza
 - ideviceinstaller
 - appinst

appinst just told me `install failed`, the other two told me that the `device has reached the maximum number of installed apps`:

```
Install: SandboxingApplication (80%)ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008021: This device has reached the maximum number of installed apps using a free developer profile: {(
    "92U4AB62QR.com.jschiefner.shopping-list-ios",
    "92U4AB62QR.com.odysseyteam.taurine.92U4AB62QR",
    "92U4AB62QR.com.92U4AB62QR.com.rileytestut.AltStore"
)}
```

I thought AppSync circumvented this problem, is there anything i did wrong?

**Comment by jschiefner** [comment]
(i restarted the device twice and also used `ldrestart`, neither helped unfortunately)

**Comment by ViRb3** [comment]
As far as I'm aware, no, AppSync will not allow you to exceed the free app limit. However, AppSync will allow you to install **unsigned** or **fakesigned** apps, which will not count towards this limit. So all you need to do is either strip the codesign of your apps, or self-sign them like you would on macOS.

**Comment by akemin-dayo** [comment]
To clarify, AppSync Unified has the ability to ignore timed app expirations, but not the app limit… _yet_.

I _am_ looking into possibly adding this feature later down the line, since I have a vague idea of where I could possibly make the modifications work.

**Comment by jschiefner** [comment]
Thanks to both of you for clarifying! I missed that part 🙉 Just for the record and for anyone else seeing this, there is now a tweak that allows one to install more than 3 apps, its called [NoFreeAppLimit](https://havoc.app/package/nofreeapplimit).
