### ISSUE TITLE
Possible iOS 4 support?

### ISSUE THREAD

**Issue by SKCro** [akemin-dayo/AppSync#95]
I'm trying to sideload an IPA onto my iPod touch running iOS 4.2.1 (the latest it can run), but apparently, this tool only supports iOS 5 and up. Is there a possibility to add iOS 4 support, or is there an alternative with iOS 4 support?

Thanks

**Comment by akemin-dayo** [comment]
iOS 4 support is considered out-of-scope for AppSync Unified, and I have no plans to support it.

That being said… the original "AppSync for iOS 4.0" created by Hackulous (no affiliation to either me or Linus Yang) should meet your needs on iOS 4.

You can get a known clean copy of that here: https://cydia.akemi.ai/?page/net.angelxwind.appsync40plus

**Comment by SKCro** [comment]
Thanks for your time. I will use that, thank you so much!
